kit_version: 0.2.0a4
aspects:
  sdd:
    depth: 3
    enabled_at: '2026-04-24T07:38:44+00:00'
    config: {}
  worktrees:
    depth: 2
    enabled_at: '2026-04-24T07:38:44+00:00'
    config: {}
  release:
    depth: 2
    enabled_at: '2026-04-24T08:25:27+00:00'
    config: {}
  testing:
    depth: 3
    enabled_at: '2026-04-24T20:19:56+00:00'
    config: {}
