kit_version: 0.2.0a6
aspects:
  kanon-deps:
    depth: 2
    enabled_at: '2026-04-25T03:07:38+00:00'
    config: {}
  kanon-release:
    depth: 2
    enabled_at: '2026-04-25T03:07:38+00:00'
    config: {}
  kanon-sdd:
    depth: 3
    enabled_at: '2026-04-25T03:07:38+00:00'
    config: {}
  kanon-security:
    depth: 2
    enabled_at: '2026-04-25T03:07:38+00:00'
    config: {}
  kanon-testing:
    depth: 3
    enabled_at: '2026-04-25T08:14:11+00:00'
    config:
      coverage_floor: 80
  kanon-worktrees:
    depth: 2
    enabled_at: '2026-04-25T03:07:38+00:00'
    config: {}
